database:
  type: H2
  host: localhost
  port: 3306
  name: dcore
  user: root
  pass: ""

economies:
  coins:
    display: "<gold>Coins</gold>"
    icon: GOLD_NUGGET
    start_balance: 100.0
    baltop:
      enabled: true
      gui: false
      size: 27
      title: "<gold>Coins Top</gold>"
  gems:
    display: "<aqua>Gems</aqua>"
    icon: hdb-7129
    start_balance: 0.0
    baltop:
      enabled: true
      gui: true
      size: 27
      title: "<aqua>Gems Top</aqua>"